spring:
  application:
    name: MapMatching

barefoot:
  postgis:
    host: localhost
    port: 5433
    database: postgres
    table: bfmap_ways
    user: postgres
    pass: postgres

  matcher:
    sigma: 45
    lambda: 0.0
    maxradius: 75
    maxdistance: 1000
    mindistance: 0
    mininterval: 900
    costfunction: distance
